[package]
name = "roll your own"
version = "0.1.0"

[dependencies]
core = { git = "https://github.com/starkware-libs/cairo.git", version = "1.0.0-alpha.3", rev = "57782f2532ee6d589432ebc3d39cf3daae863e7f" }
dojo = { git = "https://github.com/dojoengine/dojo.git" }

[[target.dojo]]
